traversability_map_visualization:
  ros__parameters:
    grid_map_topic: /traversability_estimation/traversability_map
    grid_map_visualizations:
      - traversability_map
      - slope_map
      - step_map
      - traversability_cloud

    traversability_map:
      type: occupancy_grid
      params:
        layer: traversability
        data_min: 0.0
        data_max: 1.0

    slope_map:
      type: occupancy_grid
      params:
        layer: traversability_slope
        data_min: 0.0
        data_max: 1.0

    step_map:
      type: occupancy_grid
      params:
        layer: traversability_step
        data_min: 0.0
        data_max: 1.0

    traversability_cloud:
      type: point_cloud
      params:
        layer: elevation
